version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: real_estate_db
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongo
